# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7d847bf665d3de839e8d82e52501badd7438da2cf5df72ba8e056a73bac8940686a9fa80f272b1cbbacf6555c177e1bd7833bf6ac8f5fd221f3f80fdefd25a2

test:
  secret_key_base: 868f5bd3b6df15374978e57aacf7f41249f407aec11f6b5bf0128470aa4b8bfc17acf3e6069da13d54254af8e5c118f6491728c41f493c7d058cd9acb057b34e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
